apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: tnrgus/demo-app
  newName: tnrgus/demo-app
  newTag: latest
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
