apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: tnrgus/front-app
  newName: tnrgus/front-app
  newTag: 342aa
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
